# Generated by Django 5.1 on 2024-09-28 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='status',
            field=models.CharField(choices=[('Уволен', 'Уволен'), ('На отпуске', 'На отпуске'), ('Работает', 'Работает')], default='Работает', max_length=50),
        ),
    ]
