# Generated by Django 5.1 on 2024-09-30 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_teacher_description_teacher_phone_teacher_whatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='financerecord',
            name='category',
            field=models.CharField(blank=True, choices=[('income', 'Доход'), ('expense', 'Расход')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='financerecord',
            name='name',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='financerecord',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_records', to='core.student'),
        ),
        migrations.AddField(
            model_name='financerecord',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_records', to='core.teacher'),
        ),
        migrations.AlterField(
            model_name='financerecord',
            name='type',
            field=models.CharField(max_length=50),
        ),
    ]
