# Generated by Django 5.1 on 2024-10-01 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_financerecord_category_financerecord_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financerecord',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_records', to='core.branch'),
        ),
        migrations.AddField(
            model_name='financerecord',
            name='time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
