# Generated by Django 5.1 on 2024-10-01 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_financerecord_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financerecord',
            name='time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
