# Generated by Django 5.1 on 2024-10-03 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_financerecord_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financerecord',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
