# Generated by Django 5.1 on 2024-10-03 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_financerecord_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financerecord',
            name='category',
            field=models.CharField(blank=True, choices=[('Доход', 'Доход'), ('Расход', 'Расход')], max_length=20, null=True),
        ),
    ]
