# Generated by Django 5.1 on 2024-10-08 23:02

import django.db.models.deletion
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_financerecord_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='is_attendant',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lessonschedule',
            name='days_of_week',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Понедельник', 'Понедельник'), ('Вторник', 'Вторник'), ('Среда', 'Среда'), ('Четверг', 'Четверг'), ('Пятница', 'Пятница'), ('Суббота', 'Суббота'), ('Воскресенье', 'Воскресенье')], default=['Понедельник', 'Среда'], max_length=61),
        ),
        migrations.AlterField(
            model_name='workschedule',
            name='days_of_week',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Понедельник', 'Понедельник'), ('Вторник', 'Вторник'), ('Среда', 'Среда'), ('Четверг', 'Четверг'), ('Пятница', 'Пятница'), ('Суббота', 'Суббота'), ('Воскресенье', 'Воскресенье')], default=['Понедельник', 'Среда'], max_length=61),
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.group')),
            ],
        ),
        migrations.AlterField(
            model_name='attendance',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.lesson'),
        ),
    ]
