# Generated by Django 5.1 on 2024-10-08 23:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_attendance_is_attendant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
